<!DOCTYPE html>
<!--
-	website-7 "LearnCoreJava"
-	Developed | Designed by Mayank
-	Copyright by Mayank
-	HTML : ./data/html/try_catch.html
-->
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mayank</title>
    <!--
    	---------
    	| style |
    	---------
    -->
    <link rel="stylesheet" href="../../css/style.css">
</head>

<body>
    
    <!--
    	----------------------------------------------------------------------
		| main | mother container fluid of the all code
		----------------------------------------------------------------------
    -->
    <div class="container_fluid" id="">
        
        <h1> try catch </h1>
        
        <ul>
            <li> try catch block is use for handling {Checked OR Unchecked} both Exceptions. </li>
            <li> try block inside programmer write exception code and stop to crase program. </li>
            <li> catch function that use to exception handling. </li>
            <li> catch function take arugments as "java.lang.Exception"; </li>
            <li> we are use multiple  try catch in one program. </li>
            <li> we are use multiple catch function with one try. </li>
        </ul>
        
        <h3> follow control </h3>

        <ol>
	        <li> if try block code cause exception  control goto catchfunction. </li>
	        <li> catch funtion check if exception class handle exception. </li>
	        <li> if handle so execute catch block else go next catch function. </li>
	        <li> if exception handled so control follow try ctach last end block out side. </li>
        </ol>
        
<pre class="console3">
try { //exception code } catch(ExceptionClass error_object) { //handling  }
</pre>

        <h4> example </h4>
        
<pre class="console1">
class Test
{
	public static void main(String args[])
	{
		try
		{
			System.out.println(args[0]);
		}
		catch(java.lang.ArrayIndexOutOfBoundsException error)
		{
			System.out.println(" PLEASE PASS ARGUMENT AT INTERATE TIME");
		}
		catch(Exception error)
		{
			System.out.println(" UNSEEN ERROR "+error.getMessage());
		}
		System.out.println(" execute");
	}
}
</pre>

        <h4> output </h4>
        
<pre class="console2">
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at Test.main(try_catch.java:24)

// --------------------------------------------------------------
 PLEASE PASS ARGUMENT AT INTERATE TIME
 execute
</pre>

    </div>
    <!--
    	----------
    	| script |
    	----------
    -->
    <script src="../../js/script.js"></script>

</body>

</html>
<!-- the end -->
